
package com.cisco.schemas.ast.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RISService70", targetNamespace = "http://schemas.cisco.com/ast/soap", wsdlLocation = "file:/E:/eclipse-workspace/axl-demo/wsdl/RISService70.wsdl")
public class RISService70
    extends Service
{

    private final static URL RISSERVICE70_WSDL_LOCATION;
    private final static WebServiceException RISSERVICE70_EXCEPTION;
    private final static QName RISSERVICE70_QNAME = new QName("http://schemas.cisco.com/ast/soap", "RISService70");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/E:/eclipse-workspace/axl-demo/wsdl/RISService70.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RISSERVICE70_WSDL_LOCATION = url;
        RISSERVICE70_EXCEPTION = e;
    }

    public RISService70() {
        super(__getWsdlLocation(), RISSERVICE70_QNAME);
    }

    public RISService70(WebServiceFeature... features) {
        super(__getWsdlLocation(), RISSERVICE70_QNAME, features);
    }

    public RISService70(URL wsdlLocation) {
        super(wsdlLocation, RISSERVICE70_QNAME);
    }

    public RISService70(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RISSERVICE70_QNAME, features);
    }

    public RISService70(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RISService70(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RisPortType
     */
    @WebEndpoint(name = "RisPort70")
    public RisPortType getRisPort70() {
        return super.getPort(new QName("http://schemas.cisco.com/ast/soap", "RisPort70"), RisPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RisPortType
     */
    @WebEndpoint(name = "RisPort70")
    public RisPortType getRisPort70(WebServiceFeature... features) {
        return super.getPort(new QName("http://schemas.cisco.com/ast/soap", "RisPort70"), RisPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RISSERVICE70_EXCEPTION!= null) {
            throw RISSERVICE70_EXCEPTION;
        }
        return RISSERVICE70_WSDL_LOCATION;
    }

}
